# Generated by Django 6.0.2 on 2026-03-05 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Vaqt'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.category', verbose_name='Kategoriya'),
        ),
    ]
