# Generated by Django 6.0.2 on 2026-03-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_time_transaction_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Vaqt'),
        ),
    ]
